name: BryanMiguel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34013
title: The Portfolio of Bryan Miguel – Advertising Copywriter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.24473333288915455
  lightness: 0.023352099815383554
  saturation: 0.5990364497993141
  rhythmicContrast: 0.5036235388834029
purpose: []
