name: BryanMiguel
favicon: null
layout_spectrum: 0.66705
typography_spectrum: 0.6616
title: The Portfolio of Bryan Miguel – Advertising Copywriter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1d4d9'
    - '#66402a'
    - '#848277'
    - '#baa19c'
    - '#7dd2eb'
  brandStrength: 0.625
  lightness: 0.023352099815383554
  saturation: 0.5990364497993141
  rhythmicContrast: 0.5036235388834029
purpose: []
